# Generated by Django 5.1.4 on 2025-06-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_occupation_subcategory'),
        ('users', '0004_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='occupation_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='occupation_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_subcategory'),
            preserve_default=False,
        ),
    ]
