# Generated by Django 5.1.4 on 2025-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_occupation_user_occupation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.TextField(default=1, help_text='Comma-separated keywords'),
            preserve_default=False,
        ),
    ]
