# Generated by Django 5.1.4 on 2025-06-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_occupation_subcategory'),
        ('users', '0006_user_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_subcategory'),
        ),
    ]
