# Generated by Django 5.1.4 on 2025-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_occupation_alter_user_occupation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_card_image',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='go_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_video',
            field=models.FileField(blank=True, null=True, upload_to='user_videos/'),
        ),
    ]
