# Generated by Django 5.1.4 on 2025-06-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_aadhaar_card_image_user_go_live_user_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
