# Generated by Django 5.1.4 on 2025-05-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamcomplaint',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='scamcomplaint',
            name='social_media',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
