# Generated by Django 5.1.4 on 2025-05-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_scamcomplaint_social_media_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamcomplaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
