# Generated by Django 5.1.4 on 2025-05-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_scamcomplaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamcomplaint',
            name='category',
        ),
    ]
