# Generated by Django 5.1.4 on 2025-05-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_scamcomplaint_category'),
        ('masters', '0003_scamcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamcomplaint',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.scamcategory'),
            preserve_default=False,
        ),
    ]
