# Generated by Django 5.1.4 on 2025-07-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_scamcomplaint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='customer.scamcomplaint')),
            ],
        ),
    ]
