# Generated by Django 5.1.4 on 2025-07-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_scamsocialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamcomplaint',
            name='social_media',
        ),
    ]
