# Generated by Django 5.1.4 on 2025-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_scamcomplaint_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamcomplaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('mark_as_safe', 'Mark As Safe'), ('mark_as_scam', 'Mark As Scam')], default='pending', max_length=20),
        ),
    ]
