# Generated by Django 5.1.4 on 2025-06-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_scamcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='occupation_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('occupation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_category')),
            ],
        ),
    ]
