# Generated by Django 5.1.4 on 2025-06-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_occupation_category_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='occupation_category',
            new_name='category',
        ),
    ]
