# Generated by Django 5.1.4 on 2025-06-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_rename_occupation_category_occupation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='occupation_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_category')),
            ],
        ),
    ]
