# Generated by Django 5.1.4 on 2025-06-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_occupation_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.occupation_subcategory'),
            preserve_default=False,
        ),
    ]
