# Generated by Django 5.1.4 on 2025-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_occupation_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_banner',
            name='description',
        ),
        migrations.AddField(
            model_name='home_banner',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
